### ISSUE TITLE
Use same color for multi-color

### ISSUE THREAD

**Issue by elvisvoer** [airtame/airtame-icons#5]
Design should export all SVGs to have the same base color used for multi-color (layered) icons.

**Comment by mmellado** [comment]
I think this is a very good Idea. It would bring consistency to the way we see/think of the Icons at the moment of implementing. Bringing the idea to a "higher level" this is what I would envision.

Single layered icons (1 color): by default they should be provided in white. Right now, all icons are black by default and we paint them white in the demo site to look fine with the background. That being said, on actual implementation, we will be using the icons in white so I think it would be nice for the default for these icons to be white.

Multi layered icons (multiple colors): To have the same "way of thought" when it comes to these icons I feel like it should be based on themes, just like @noahlaux suggested yesterday. I would say, we'd have 5 themes:

* white (main color white, secondary color dark blue as the background)
* Grey (main color grey, secondary the same as above? not sure)
* Blue (2 shades of blue)
* Green (2 shades of green)
* Yellow (2 shades of yellow)
* Red (2 shades of red)

This would be beneficial due to the following reasons:

- Provides a unified way (theme) of consumption by default, so thinking about icons doesn't require to think on what theme should I expect by default
- Standardized way of thinking about how to modify the icons by default (knowing I'll get it white and what I need to do to make it look blue)
- Provide a standard way of applying these themes through css by a CSS/SCSS file which takes care of handling the icons (should it be mixins, should it be plain css?)

Would love to get @elvisvoer and @madshensel  thoughts on this.

**Comment by madshensel** [comment]
A downside I see if I understand it correctly is that we need to define the secondary color as ex. the dark background to fake a knockout icon where the background would otherwise be visible through. Is this ideal? What if we want to use the icons on a white background or even on an item where the background change on hover. You can control this via CSS, but that just seems like adding complexity.

If the icon has two colors I doubt it's going to be used as a single color icon.

We could provide a single color version for all icons and for the ones that have multicolor also have that. So in some case two versions.

**Comment by elvisvoer** [comment]
@madshensel what we meant was the following:

1. decide if the single color icon default color should be black or white.
2. for multi color icons there should be a unified color scheme used as default. If you access this link:
https://airtame.github.io/airtame-icons/ all multi color icons should be for instance the green and black combo we have for `icon-box-badge-mc.svg`.

Why would I have `icon-emoji-happy-mc.svg`, `icon-emoji-neutral-mc.svg` and `icon-emoji-sad-mc.svg` with 3 default colors? Does this make more sense?

**Comment by madshensel** [comment]
I think it's very much up to you in the front-end group how you want it to be implemented and work with it. But here's my input.
1. White makes sense since that's what we're using the most right now.
2. I think it makes sense with three different colors as the multicolored icon in most cases are unique and properly won't change color. Then again this might happen and hens a scheme would be a good solution.
